### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by atelier-yuki** [atelier-yuki/protospace-32499#1]
# URL
https://protospace-32499.herokuapp.com/

**Comment by checker-ms** [comment]
atelier-yuki様

ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[現状]
①ログアウトの状態だと、プロトタイプが一覧表示されていない（ログインページが表示されている）
②ログアウト状態のユーザーでも、投稿ページへ遷移できる

[修正箇所]
①ログイン・ログアウトの状態に関わらず、一覧表示されている画像をクリックすると、該当する詳細ページへ遷移すること
②ログイン状態のユーザーだけが、投稿ページへ遷移できること

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by atelier-yuki** [comment]
> atelier-yuki様
> 
> ご提出ありがとうございます！
> 挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
> 
> [現状]
> ①ログアウトの状態だと、プロトタイプが一覧表示されていない（ログインページが表示されている）
> ②ログアウト状態のユーザーでも、投稿ページへ遷移できる
> 
> [修正箇所]
> ①ログイン・ログアウトの状態に関わらず、一覧表示されている画像をクリックすると、該当する詳細ページへ遷移すること
> ②ログイン状態のユーザーだけが、投稿ページへ遷移できること
> 
> 修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
> ※新しいissueを作っていただく必要はありません
> 
> https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by atelier-yuki** [comment]
> > atelier-yuki様
> > ご提出ありがとうございます！
> > 挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
> > [現状]
> > ①ログアウトの状態だと、プロトタイプが一覧表示されていない（ログインページが表示されている）
> > ②ログアウト状態のユーザーでも、投稿ページへ遷移できる
> > [修正箇所]
> > ①ログイン・ログアウトの状態に関わらず、一覧表示されている画像をクリックすると、該当する詳細ページへ遷移すること
> > ②ログイン状態のユーザーだけが、投稿ページへ遷移できること
> > 修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
> > ※新しいissueを作っていただく必要はありません
> > https://forms.gle/ZdLeprTTWhMA8aZA7

上記修正いたしました。

**Comment by checker-ms** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[現状]
ログアウト状態のユーザーで、編集ページへ遷移しようとすると、ログインページにリダイレクトされない

[修正箇所]
ログアウト状態のユーザーは、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページ以外のページに遷移しようとすると、ログインページにリダイレクトされること
![Uploading image.png…]()


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by atelier-yuki** [comment]
上記修正いたしました。

**Comment by checker-ms** [comment]
修正とご提出ありがとうございます！

挙動確認させていただいたところ、全く問題ありませんでしたので、LGTMとさせていただきます🎉

実装お疲れ様でした。おめでとうございます！
